services:
  - type: web
    name: portfolio-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000

  - type: web
    name: portfolio-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/Portfolio
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
